# Generated by Django 4.0.5 on 2022-08-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor_mensaje', models.CharField(max_length=50)),
                ('receptor_mensaje', models.CharField(max_length=50)),
                ('fecha_mensaje', models.DateField(auto_now=True)),
                ('texto_mensaje', models.TextField(blank=True, null=True)),
                ('leido_mensaje', models.BooleanField(default=False)),
                ('imagen_mensaje', models.ImageField(blank=True, null=True, upload_to='mensajes')),
            ],
        ),
    ]
