# Generated by Django 4.0.5 on 2022-08-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='fecha_mensaje',
            field=models.DateField(),
        ),
    ]
